// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MondayApi.Schema
{
    public enum AccountProductKind
    {
        [EnumMember(Value = "core")] Core,
        [EnumMember(Value = "marketing")] Marketing,
        [EnumMember(Value = "crm")] Crm,
        [EnumMember(Value = "software")] Software,
        projectManagement,
        [EnumMember(Value = "project_management")] ProjectManagement,
        [EnumMember(Value = "forms")] Forms,
        [EnumMember(Value = "whiteboard")] Whiteboard
    }
}
