// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MondayApi.Schema
{
    public class Account
    {
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("country_code")]
        #endif
        public string CountryCode { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("first_day_of_the_week")]
        #endif
        public FirstDayOfTheWeek? FirstDayOfTheWeek { get; set; }
        public int? Id { get; set; }
        public string Logo { get; set; }
        public string Name { get; set; }
        public Plan Plan { get; set; }
        public ICollection<AccountProduct> Products { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("show_timeline_weekends")]
        #endif
        public bool? ShowTimelineWeekends { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("sign_up_product_kind")]
        #endif
        public string SignUpProductKind { get; set; }
        public string Slug { get; set; }
        public string Tier { get; set; }
    }
}
