// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MondayApi.Schema
{
    public class AccountProductQueryBuilder : GraphQlQueryBuilder<AccountProductQueryBuilder>
    {
        private static readonly GraphQlFieldMetadata[] AllFieldMetadata =
            new []
            {
                new GraphQlFieldMetadata { Name = "id" },
                new GraphQlFieldMetadata { Name = "kind" }
            };

        protected override string TypeName { get { return "AccountProduct"; } } 

        public override IReadOnlyList<GraphQlFieldMetadata> AllFields { get { return AllFieldMetadata; } } 

        public AccountProductQueryBuilder WithId(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("id", alias, new GraphQlDirective[] { include, skip });
        }

        public AccountProductQueryBuilder ExceptId()
        {
            return ExceptField("id");
        }

        public AccountProductQueryBuilder WithKind(string alias = null, IncludeDirective include = null, SkipDirective skip = null)
        {
            return WithScalarField("kind", alias, new GraphQlDirective[] { include, skip });
        }

        public AccountProductQueryBuilder ExceptKind()
        {
            return ExceptField("kind");
        }
    }
}
