// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MondayApi.Schema
{
    public enum BoardAttributes
    {
        [EnumMember(Value = "name")] Name,
        [EnumMember(Value = "description")] Description,
        [EnumMember(Value = "communication")] Communication
    }
}
