// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MondayApi.Schema
{
    public class Column
    {
        public bool? Archived { get; set; }
        public string Description { get; set; }
        public Guid? Id { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("settings_str")]
        #endif
        public string SettingsStr { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public int? Width { get; set; }
    }
}
