// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MondayApi.Schema
{
    public class ColumnValue
    {
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("additional_info")]
        #endif
        public object AdditionalInfo { get; set; }
        public string Description { get; set; }
        public Guid? Id { get; set; }
        public string Text { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public object Value { get; set; }
    }
}
