// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MondayApi.Schema
{
    public class CreateDocBoardInput : IGraphQlInputObject
    {
        private InputPropertyInfo _itemId;
        private InputPropertyInfo _columnId;

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("item_id")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<Guid?>))]
        #endif
        public QueryBuilderParameter<Guid?> ItemId
        {
            get { return (QueryBuilderParameter<Guid?>)_itemId.Value; }
            set { _itemId = new InputPropertyInfo { Name = "item_id", Value = value }; }
        }

        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("column_id")]
        [JsonConverter(typeof(QueryBuilderParameterConverter<string>))]
        #endif
        public QueryBuilderParameter<string> ColumnId
        {
            get { return (QueryBuilderParameter<string>)_columnId.Value; }
            set { _columnId = new InputPropertyInfo { Name = "column_id", Value = value }; }
        }

        IEnumerable<InputPropertyInfo> IGraphQlInputObject.GetPropertyValues()
        {
            if (_itemId.Name != null) yield return _itemId;
            if (_columnId.Name != null) yield return _columnId;
        }
    }
}
