// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MondayApi.Schema
{
    public enum DocsOrderBy
    {
        [EnumMember(Value = "created_at")] CreatedAt,
        [EnumMember(Value = "used_at")] UsedAt
    }
}
