// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MondayApi.Schema
{
    public class Document
    {
        public ICollection<DocumentBlock> Blocks { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("created_at")]
        #endif
        public DateTimeOffset? CreatedAt { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("created_by")]
        #endif
        public User CreatedBy { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("doc_folder_id")]
        #endif
        public int? DocFolderId { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("doc_kind")]
        #endif
        public BoardKind? DocKind { get; set; }
        public int? Id { get; set; }
        public string Name { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("object_id")]
        #endif
        public int? ObjectId { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("relative_url")]
        #endif
        public string RelativeUrl { get; set; }
        public object Settings { get; set; }
        public string Url { get; set; }
        public Workspace Workspace { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("workspace_id")]
        #endif
        public int? WorkspaceId { get; set; }
    }
}
