// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MondayApi.Schema
{
    public enum DuplicateBoardType
    {
        [EnumMember(Value = "duplicate_board_with_structure")] DuplicateBoardWithStructure,
        [EnumMember(Value = "duplicate_board_with_pulses")] DuplicateBoardWithPulses,
        [EnumMember(Value = "duplicate_board_with_pulses_and_updates")] DuplicateBoardWithPulsesAndUpdates
    }
}
