// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MondayApi.Schema
{
    public class Folder
    {
        public ICollection<Board> Children { get; set; }
        public FolderColor? Color { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("created_at")]
        #endif
        public DateTimeOffset? CreatedAt { get; set; }
        public int? Id { get; set; }
        public string Name { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("owner_id")]
        #endif
        public int? OwnerId { get; set; }
        public Folder Parent { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("sub_folders")]
        #endif
        public ICollection<Folder> SubFolders { get; set; }
        public Workspace Workspace { get; set; }
    }
}
