// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MondayApi.Schema
{
    public class Group
    {
        public bool? Archived { get; set; }
        public string Color { get; set; }
        public bool? Deleted { get; set; }
        public Guid? Id { get; set; }
        public string Position { get; set; }
        public string Title { get; set; }
    }
}
