// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MondayApi.Schema
{
    public class Item
    {
        public ICollection<Asset> Assets { get; set; }
        public Board Board { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("column_values")]
        #endif
        public ICollection<ColumnValue> ColumnValues { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("created_at")]
        #endif
        public DateTimeOffset? CreatedAt { get; set; }
        public User Creator { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("creator_id")]
        #endif
        public string CreatorId { get; set; }
        public string Email { get; set; }
        public Group Group { get; set; }
        public Guid? Id { get; set; }
        public string Name { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("parent_item")]
        #endif
        public Item ParentItem { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("relative_link")]
        #endif
        public string RelativeLink { get; set; }
        public State? State { get; set; }
        public ICollection<Item> Subitems { get; set; }
        public ICollection<User> Subscribers { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("updated_at")]
        #endif
        public DateTimeOffset? UpdatedAt { get; set; }
        public ICollection<Update> Updates { get; set; }
    }
}
