// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MondayApi.Schema
{
    public class Mutation
    {
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("add_file_to_column")]
        #endif
        public Asset AddFileToColumn { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("add_file_to_update")]
        #endif
        public Asset AddFileToUpdate { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("add_teams_to_board")]
        #endif
        public ICollection<Team> AddTeamsToBoard { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("add_teams_to_workspace")]
        #endif
        public ICollection<Team> AddTeamsToWorkspace { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("add_users_to_board")]
        #endif
        public ICollection<User> AddUsersToBoard { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("add_users_to_workspace")]
        #endif
        public ICollection<User> AddUsersToWorkspace { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("archive_board")]
        #endif
        public Board ArchiveBoard { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("archive_group")]
        #endif
        public Group ArchiveGroup { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("archive_item")]
        #endif
        public Item ArchiveItem { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("change_column_metadata")]
        #endif
        public Column ChangeColumnMetadata { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("change_column_title")]
        #endif
        public Column ChangeColumnTitle { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("change_column_value")]
        #endif
        public Item ChangeColumnValue { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("change_multiple_column_values")]
        #endif
        public Item ChangeMultipleColumnValues { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("change_simple_column_value")]
        #endif
        public Item ChangeSimpleColumnValue { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("clear_item_updates")]
        #endif
        public Item ClearItemUpdates { get; set; }
        public Complexity Complexity { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("create_board")]
        #endif
        public Board CreateBoard { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("create_column")]
        #endif
        public Column CreateColumn { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("create_doc")]
        #endif
        public Document CreateDoc { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("create_doc_block")]
        #endif
        public DocumentBlock CreateDocBlock { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("create_folder")]
        #endif
        public Folder CreateFolder { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("create_group")]
        #endif
        public Group CreateGroup { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("create_item")]
        #endif
        public Item CreateItem { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("create_notification")]
        #endif
        public Notification CreateNotification { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("create_or_get_tag")]
        #endif
        public Tag CreateOrGetTag { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("create_subitem")]
        #endif
        public Item CreateSubitem { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("create_update")]
        #endif
        public Update CreateUpdate { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("create_webhook")]
        #endif
        public Webhook CreateWebhook { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("create_workspace")]
        #endif
        public Workspace CreateWorkspace { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("delete_board")]
        #endif
        public Board DeleteBoard { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("delete_column")]
        #endif
        public Column DeleteColumn { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("delete_doc_block")]
        #endif
        public DocumentBlockIdOnly DeleteDocBlock { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("delete_folder")]
        #endif
        public Folder DeleteFolder { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("delete_group")]
        #endif
        public Group DeleteGroup { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("delete_item")]
        #endif
        public Item DeleteItem { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("delete_subscribers_from_board")]
        #endif
        public ICollection<User> DeleteSubscribersFromBoard { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("delete_teams_from_workspace")]
        #endif
        public ICollection<Team> DeleteTeamsFromWorkspace { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("delete_update")]
        #endif
        public Update DeleteUpdate { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("delete_users_from_workspace")]
        #endif
        public ICollection<User> DeleteUsersFromWorkspace { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("delete_webhook")]
        #endif
        public Webhook DeleteWebhook { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("delete_workspace")]
        #endif
        public Workspace DeleteWorkspace { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("duplicate_board")]
        #endif
        public BoardDuplication DuplicateBoard { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("duplicate_group")]
        #endif
        public Group DuplicateGroup { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("duplicate_item")]
        #endif
        public Item DuplicateItem { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("like_update")]
        #endif
        public Update LikeUpdate { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("move_item_to_group")]
        #endif
        public Item MoveItemToGroup { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("remove_mock_app_subscription")]
        #endif
        public AppSubscription RemoveMockAppSubscription { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("set_mock_app_subscription")]
        #endif
        public AppSubscription SetMockAppSubscription { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("update_board")]
        #endif
        public object UpdateBoard { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("update_doc_block")]
        #endif
        public DocumentBlock UpdateDocBlock { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("update_folder")]
        #endif
        public Folder UpdateFolder { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("update_group")]
        #endif
        public Group UpdateGroup { get; set; }
    }
}
