// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MondayApi.Schema
{
    public class User
    {
        public Account Account { get; set; }
        public object Birthday { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("country_code")]
        #endif
        public string CountryCode { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("created_at")]
        #endif
        public DateTimeOffset? CreatedAt { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("current_language")]
        #endif
        public string CurrentLanguage { get; set; }
        public string Email { get; set; }
        public bool? Enabled { get; set; }
        public int? Id { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("is_admin")]
        #endif
        public bool? IsAdmin { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("is_guest")]
        #endif
        public bool? IsGuest { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("is_pending")]
        #endif
        public bool? IsPending { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("is_verified")]
        #endif
        public bool? IsVerified { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("is_view_only")]
        #endif
        public bool? IsViewOnly { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("join_date")]
        #endif
        public object JoinDate { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("last_activity")]
        #endif
        public object LastActivity { get; set; }
        public string Location { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("mobile_phone")]
        #endif
        public string MobilePhone { get; set; }
        public string Name { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("out_of_office")]
        #endif
        public OutOfOffice OutOfOffice { get; set; }
        public string Phone { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("photo_original")]
        #endif
        public string PhotoOriginal { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("photo_small")]
        #endif
        public string PhotoSmall { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("photo_thumb")]
        #endif
        public string PhotoThumb { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("photo_thumb_small")]
        #endif
        public string PhotoThumbSmall { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("photo_tiny")]
        #endif
        public string PhotoTiny { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("sign_up_product_kind")]
        #endif
        public string SignUpProductKind { get; set; }
        public ICollection<Team> Teams { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("time_zone_identifier")]
        #endif
        public string TimeZoneIdentifier { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("utc_hours_diff")]
        #endif
        public int? UtcHoursDiff { get; set; }
    }
}
