// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MondayApi.Schema
{
    public enum UserKind
    {
        [EnumMember(Value = "all")] All,
        [EnumMember(Value = "non_guests")] NonGuests,
        [EnumMember(Value = "guests")] Guests,
        [EnumMember(Value = "non_pending")] NonPending
    }
}
