// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MondayApi.Schema
{
    public enum VersionKind
    {
        [EnumMember(Value = "deprecated")] Deprecated,
        [EnumMember(Value = "stable")] Stable,
        [EnumMember(Value = "preview")] Preview,
        [EnumMember(Value = "dev")] Dev
    }
}
