// <auto-generated> This file has been auto generated. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
#if!GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
using Newtonsoft.Json;
#endif

namespace MondayApi.Schema
{
    public class Workspace
    {
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("account_product")]
        #endif
        public AccountProduct AccountProduct { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("created_at")]
        #endif
        public DateTimeOffset? CreatedAt { get; set; }
        public string Description { get; set; }
        public int? Id { get; set; }
        public WorkspaceKind? Kind { get; set; }
        public string Name { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("owners_subscribers")]
        #endif
        public ICollection<User> OwnersSubscribers { get; set; }
        public WorkspaceSettings Settings { get; set; }
        public State? State { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("team_owners_subscribers")]
        #endif
        public ICollection<Team> TeamOwnersSubscribers { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("teams_subscribers")]
        #endif
        public ICollection<Team> TeamsSubscribers { get; set; }
        #if !GRAPHQL_GENERATOR_DISABLE_NEWTONSOFT_JSON
        [JsonProperty("users_subscribers")]
        #endif
        public ICollection<User> UsersSubscribers { get; set; }
    }
}
